# Generated by Django 3.1.3 on 2020-11-09 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcompany', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-created',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='slidermodel',
            options={'ordering': ('-created',), 'verbose_name': 'Слайд', 'verbose_name_plural': 'Все слайды'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vcompany.category'),
            preserve_default=False,
        ),
    ]
