# Generated by Django 3.1.3 on 2020-11-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcompany', '0002_auto_20201109_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_src',
            field=models.ImageField(blank=True, upload_to='img/products/%Y/%m', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='slidermodel',
            name='image_src',
            field=models.ImageField(blank=True, upload_to='img/sliders', verbose_name='слайд'),
        ),
    ]
