# Generated by Django 3.1.3 on 2020-11-21 17:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vcompany', '0003_auto_20201109_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст статьи'),
        ),
    ]
