# Generated by Django 3.1.3 on 2020-11-21 17:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vcompany', '0004_auto_20201121_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('text', tinymce.models.HTMLField(verbose_name='Текст статьи')),
            ],
            options={
                'verbose_name': 'Отдельная информационная страница',
                'verbose_name_plural': 'Информационные страницы разделов',
            },
        ),
    ]
