# Generated by Django 3.1.3 on 2020-11-22 10:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vcompany', '0005_singlepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text_ch',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст статьи китайский'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст статьи англ'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ch',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='перевод китайский'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='перевод англ'),
        ),
        migrations.AddField(
            model_name='singlepage',
            name='text_ch',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст страницы китайский'),
        ),
        migrations.AddField(
            model_name='singlepage',
            name='text_en',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Текст страницы англ'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='title_ch',
            field=models.CharField(blank=True, max_length=255, verbose_name='китайский'),
        ),
        migrations.AddField(
            model_name='slidermodel',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='англ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='название русский'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='singlepage',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Текст страницы'),
        ),
    ]
