# Generated by Django 3.1.3 on 2021-03-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcompany', '0007_indexmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexmodel',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='vcompany.category'),
            preserve_default=False,
        ),
    ]
